//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrozzleApplication {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConfigurationKeys {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfigurationKeys() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrozzleApplication.ConfigurationKeys", typeof(ConfigurationKeys).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAXIMUM-HORIZONTAL.
        /// </summary>
        internal static string DIRECTIONALINTERSECT_MAXIMUMHORZ {
            get {
                return ResourceManager.GetString("DIRECTIONALINTERSECT_MAXIMUMHORZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAXIMUM-VERTICAL.
        /// </summary>
        internal static string DIRECTIONALINTERSECT_MAXIMUMVERT {
            get {
                return ResourceManager.GetString("DIRECTIONALINTERSECT_MAXIMUMVERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MINIMUM-HORIZONTAL.
        /// </summary>
        internal static string DIRECTIONALINTERSECT_MINIMUMHORZ {
            get {
                return ResourceManager.GetString("DIRECTIONALINTERSECT_MINIMUMHORZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MINIMUM-VERTICAL.
        /// </summary>
        internal static string DIRECTIONALINTERSECT_MINIMUMVERT {
            get {
                return ResourceManager.GetString("DIRECTIONALINTERSECT_MINIMUMVERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INTERSECTIONS-IN-SEQUENCES.
        /// </summary>
        internal static string DIRECTIONALINTERSECT_OPENBRACKET {
            get {
                return ResourceManager.GetString("DIRECTIONALINTERSECT_OPENBRACKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAXIMUM-HORIZONTAL.
        /// </summary>
        internal static string DIRECTIONALSEQ_MAXIMUMHORZ {
            get {
                return ResourceManager.GetString("DIRECTIONALSEQ_MAXIMUMHORZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAXIMUM-VERTICAL.
        /// </summary>
        internal static string DIRECTIONALSEQ_MAXIMUMVERT {
            get {
                return ResourceManager.GetString("DIRECTIONALSEQ_MAXIMUMVERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MINIMUM-HORIZONTAL.
        /// </summary>
        internal static string DIRECTIONALSEQ_MINIMUMHORZ {
            get {
                return ResourceManager.GetString("DIRECTIONALSEQ_MINIMUMHORZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MINIMUM-VERTICAL.
        /// </summary>
        internal static string DIRECTIONALSEQ_MINIMUMVERT {
            get {
                return ResourceManager.GetString("DIRECTIONALSEQ_MINIMUMVERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEQUENCES-IN-CROZZLE.
        /// </summary>
        internal static string DIRECTIONALSEQ_OPENBRACKET {
            get {
                return ResourceManager.GetString("DIRECTIONALSEQ_OPENBRACKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAXIMUM.
        /// </summary>
        internal static string DUPE_MAXIMUMVALID {
            get {
                return ResourceManager.GetString("DUPE_MAXIMUMVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MINIMUM.
        /// </summary>
        internal static string DUPE_MINIMUMVALID {
            get {
                return ResourceManager.GetString("DUPE_MINIMUMVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DUPLICATE-SEQUENCES.
        /// </summary>
        internal static string DUPE_OPENBRACKET {
            get {
                return ResourceManager.GetString("DUPE_OPENBRACKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INTERSECTING-POINTS.
        /// </summary>
        internal static string INTERSECT_OPENBRACKET {
            get {
                return ResourceManager.GetString("INTERSECT_OPENBRACKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEFAULT.
        /// </summary>
        internal static string LOGFILE_FILENAME {
            get {
                return ResourceManager.GetString("LOGFILE_FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGFILE.
        /// </summary>
        internal static string LOGFILE_OPENBRACKET {
            get {
                return ResourceManager.GetString("LOGFILE_OPENBRACKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NON-INTERSECTING-POINTS.
        /// </summary>
        internal static string NONINTERSECT_OPENBRACKET {
            get {
                return ResourceManager.GetString("NONINTERSECT_OPENBRACKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BGCOLOUR-EMPTY-TD.
        /// </summary>
        internal static string OUTPUT_BGCOLOUR_EMPTY {
            get {
                return ResourceManager.GetString("OUTPUT_BGCOLOUR_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BGCOLOUR-NON-EMPTY-TD.
        /// </summary>
        internal static string OUTPUT_BGCOLOUR_NONEMPTY {
            get {
                return ResourceManager.GetString("OUTPUT_BGCOLOUR_NONEMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID-CROZZLE-SCORE.
        /// </summary>
        internal static string OUTPUT_INVALID {
            get {
                return ResourceManager.GetString("OUTPUT_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CROZZLE-OUTPUT.
        /// </summary>
        internal static string OUTPUT_OPENBRACKET {
            get {
                return ResourceManager.GetString("OUTPUT_OPENBRACKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STYLE.
        /// </summary>
        internal static string OUTPUT_STYLE {
            get {
                return ResourceManager.GetString("OUTPUT_STYLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPPERCASE.
        /// </summary>
        internal static string OUTPUT_UPPERCASE {
            get {
                return ResourceManager.GetString("OUTPUT_UPPERCASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAXIMUM-COLUMNS.
        /// </summary>
        internal static string SIZE_MAXIMUMCOLUMNS {
            get {
                return ResourceManager.GetString("SIZE_MAXIMUMCOLUMNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAXIMUM-ROWS.
        /// </summary>
        internal static string SIZE_MAXIMUMROWS {
            get {
                return ResourceManager.GetString("SIZE_MAXIMUMROWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MINIMUM-COLUMNS.
        /// </summary>
        internal static string SIZE_MINIMUMCOLUMNS {
            get {
                return ResourceManager.GetString("SIZE_MINIMUMCOLUMNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MINIMUM-ROWS.
        /// </summary>
        internal static string SIZE_MINIMUMROWS {
            get {
                return ResourceManager.GetString("SIZE_MINIMUMROWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CROZZLE-SIZE.
        /// </summary>
        internal static string SIZE_OPENBRACKET {
            get {
                return ResourceManager.GetString("SIZE_OPENBRACKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAXIMUM.
        /// </summary>
        internal static string UNIQUESEQ_MAXIMUM {
            get {
                return ResourceManager.GetString("UNIQUESEQ_MAXIMUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MINIMUM.
        /// </summary>
        internal static string UNIQUESEQ_MINIMUM {
            get {
                return ResourceManager.GetString("UNIQUESEQ_MINIMUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEQUENCES-IN-FILE.
        /// </summary>
        internal static string UNIQUESEQ_OPENBRACKET {
            get {
                return ResourceManager.GetString("UNIQUESEQ_OPENBRACKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAXIMUM.
        /// </summary>
        internal static string VALIDGROUP_MAXIMUM {
            get {
                return ResourceManager.GetString("VALIDGROUP_MAXIMUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MINIMUM.
        /// </summary>
        internal static string VALIDGROUP_MINIMUM {
            get {
                return ResourceManager.GetString("VALIDGROUP_MINIMUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VALID-GROUPS.
        /// </summary>
        internal static string VALIDGROUP_OPENBRACKET {
            get {
                return ResourceManager.GetString("VALIDGROUP_OPENBRACKET", resourceCulture);
            }
        }
    }
}
