//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrozzleApplication {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CrozzleFileKeys {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CrozzleFileKeys() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrozzleApplication.CrozzleFileKeys", typeof(CrozzleFileKeys).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFIG-DATA.
        /// </summary>
        internal static string DEPENDENCIES_CONFIGDATA {
            get {
                return ResourceManager.GetString("DEPENDENCIES_CONFIGDATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FILE-DEPENDENCIES.
        /// </summary>
        internal static string DEPENDENCIES_OPENBRACKET {
            get {
                return ResourceManager.GetString("DEPENDENCIES_OPENBRACKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEQUENCE-DATA.
        /// </summary>
        internal static string DEPENDENCIES_SEQDATA {
            get {
                return ResourceManager.GetString("DEPENDENCIES_SEQDATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOCATION.
        /// </summary>
        internal static string HORZSEQ_LOCATION {
            get {
                return ResourceManager.GetString("HORZSEQ_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HORIZONTAL-SEQUENCES.
        /// </summary>
        internal static string HORZSEQ_OPENBRACKET {
            get {
                return ResourceManager.GetString("HORZSEQ_OPENBRACKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEQUENCE.
        /// </summary>
        internal static string HORZSEQ_SEQUENCE {
            get {
                return ResourceManager.GetString("HORZSEQ_SEQUENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIZE.
        /// </summary>
        internal static string SIZE_DIMENSIONS {
            get {
                return ResourceManager.GetString("SIZE_DIMENSIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CROZZLE-SIZE.
        /// </summary>
        internal static string SIZE_OPENBRACKET {
            get {
                return ResourceManager.GetString("SIZE_OPENBRACKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOCATION.
        /// </summary>
        internal static string VERTSEQ_LOCATION {
            get {
                return ResourceManager.GetString("VERTSEQ_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VERTICAL-SEQUENCES.
        /// </summary>
        internal static string VERTSEQ_OPENBRACKET {
            get {
                return ResourceManager.GetString("VERTSEQ_OPENBRACKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEQUENCE.
        /// </summary>
        internal static string VERTSEQ_SEQUENCE {
            get {
                return ResourceManager.GetString("VERTSEQ_SEQUENCE", resourceCulture);
            }
        }
    }
}
