//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrozzleApplication {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DebugWarnings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DebugWarnings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrozzleApplication.DebugWarnings", typeof(DebugWarnings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code 11003: validator function result &apos;{0}&apos; conflicts with parameter result &apos;{1}&apos;.
        /// </summary>
        internal static string ConflictingBooleanWarning {
            get {
                return ResourceManager.GetString("ConflictingBooleanWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code 11004: data file &apos;{0}&apos; did not expect multiple occurrences of a Boolean.
        /// </summary>
        internal static string ExcessBooleanWarning {
            get {
                return ResourceManager.GetString("ExcessBooleanWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code 11001: data file &apos;{0}&apos; did not expect the substring &apos;{1}&apos;.
        /// </summary>
        internal static string SubStringExistsWarning {
            get {
                return ResourceManager.GetString("SubStringExistsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code 11002: a Boolean substring in &apos;{0}&apos; cannot be parsed.
        /// </summary>
        internal static string UnparseableBooleanWarning {
            get {
                return ResourceManager.GetString("UnparseableBooleanWarning", resourceCulture);
            }
        }
    }
}
